"""Pipeline component versions recorded on every AnalysisRun / AttentionPlan."""

EXTRACTOR_VERSION = "raos-extractor-0.2.2"
MATCHER_VERSION = "raos-matcher-0.3.1"
EVIDENCE_REASONER_VERSION = "raos-evidence-0.2.2"
DELTA_VERSION = "raos-delta-0.2.1"
SCHEDULER_VERSION = "raos-scheduler-0.4.0"
ATTENTION_POLICY_VERSION = "raos-attention-policy-0.4.0"
PROMPT_VERSION = "raos-prompts-0.6.1"
PROVIDER_VERSION = "raos-provider-0.6.1"
IMPACT_ASSESSOR_VERSION = "raos-impact-0.4.1"
EMBEDDING_MODEL_VERSION_NONE = "none"
PIPELINE_VERSION = "raos-pipeline-0.6.1"
